import { SingleProductProvider } from "@app/providers/SingleProductProvider";
import { StoreProvider } from "@app/providers/StoreProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ferreteria App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SingleProductProvider>
      {children}
    </SingleProductProvider>
  );
}

