import { MainFooter, MainHeader } from "@app/components/common";
import { StoreProvider } from "@app/providers/StoreProvider";
import { ThemeProvider } from "@app/providers/ThemeProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ferreteria App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: 'whitesmoke', color: 'black' }}>
        <ThemeProvider>
          <StoreProvider>
            <div style={{ display: 'grid', minHeight: '100dvh', gridTemplateRows: 'auto 1fr auto' }}>
              <MainHeader />
              {children}
              <MainFooter />
            </div>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
