import { MainFooter, MainHeader } from "@app/components/common";
import { ThemeProvider } from "@app/providers/ThemeProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ferreteria App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: 'whitesmoke' }}>
        <ThemeProvider>
          <MainHeader />
          {children}
          <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
